apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-1
  region: us-east-1c

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredcapacity: 3
    spot: true
  